"""人気ドライバーのカタログ（2021〜現行・テーラーメイド/キャロウェイ/ピン）。

model_code不要のキーワード方式。各機種は検索KWと圧縮キー（required/excludes）で
派生（兄弟）モデルを分離してマッチする。新機種はここに1行足すだけ。
"""

from dataclasses import dataclass, field


@dataclass
class DriverModel:
    key: str
    brand: str
    label: str
    year: str
    keyword: str                       # 楽天/Yahoo共通の検索KW
    required: list[str]                # 全て圧縮キーに含む必要
    excludes: list[str] = field(default_factory=list)  # 含んだら除外（兄弟分離）
    category: str = "driver"           # driver / fw / ut / iron


# カテゴリの表示名
CATEGORIES = [
    ("driver", "ドライバー"),
    ("fw", "フェアウェイウッド"),
    ("ut", "ユーティリティ"),
    ("iron", "アイアン"),
    ("chipper", "チッパー"),
]
CATEGORY_LABEL = dict(CATEGORIES)


CATALOG: list[DriverModel] = [
    # ============ テーラーメイド ============
    # --- SIM2 (2021) ---
    DriverModel("tm_sim2", "テーラーメイド", "SIM2", "2021",
                "テーラーメイド SIM2 ドライバー", ["sim2"], ["max", "fast", "mini", "ti"]),
    DriverModel("tm_sim2max", "テーラーメイド", "SIM2 MAX", "2021",
                "テーラーメイド SIM2 MAX ドライバー", ["sim2max"], ["maxd", "fast"]),
    DriverModel("tm_sim2maxd", "テーラーメイド", "SIM2 MAX-D", "2021",
                "テーラーメイド SIM2 MAX-D ドライバー", ["sim2maxd"], []),
    # --- STEALTH (2022) ---
    DriverModel("tm_stealth", "テーラーメイド", "STEALTH", "2022",
                "テーラーメイド ステルス ドライバー", ["stealth"], ["stealth2", "plus", "hd"]),
    DriverModel("tm_stealthplus", "テーラーメイド", "STEALTH Plus", "2022",
                "テーラーメイド ステルス プラス ドライバー", ["stealthplus"], ["stealth2"]),
    DriverModel("tm_stealthhd", "テーラーメイド", "STEALTH HD", "2022",
                "テーラーメイド ステルス HD ドライバー", ["stealthhd"], ["stealth2"]),
    # --- STEALTH2 (2023) ---
    DriverModel("tm_stealth2", "テーラーメイド", "STEALTH2", "2023",
                "テーラーメイド ステルス2 ドライバー", ["stealth2"], ["plus", "hd"]),
    DriverModel("tm_stealth2plus", "テーラーメイド", "STEALTH2 Plus", "2023",
                "テーラーメイド ステルス2 プラス ドライバー", ["stealth2plus"], []),
    DriverModel("tm_stealth2hd", "テーラーメイド", "STEALTH2 HD", "2023",
                "テーラーメイド ステルス2 HD ドライバー", ["stealth2hd"], []),
    # --- Qi10 (2024) ---
    DriverModel("tm_qi10", "テーラーメイド", "Qi10", "2024",
                "テーラーメイド Qi10 ドライバー", ["qi10"], ["max", "ls"]),
    DriverModel("tm_qi10max", "テーラーメイド", "Qi10 MAX", "2024",
                "テーラーメイド Qi10 MAX ドライバー", ["qi10max"], []),
    DriverModel("tm_qi10ls", "テーラーメイド", "Qi10 LS", "2024",
                "テーラーメイド Qi10 LS ドライバー", ["qi10ls"], []),

    # ============ キャロウェイ ============
    # --- ROGUE ST (2022) ---
    DriverModel("cw_roguestmax", "キャロウェイ", "ROGUE ST MAX", "2022",
                "キャロウェイ ROGUE ST MAX ドライバー", ["roguestmax"], ["maxd", "maxls", "maxfast"]),
    DriverModel("cw_roguestmaxd", "キャロウェイ", "ROGUE ST MAX D", "2022",
                "キャロウェイ ROGUE ST MAX D ドライバー", ["roguestmaxd"], []),
    DriverModel("cw_roguestmaxls", "キャロウェイ", "ROGUE ST MAX LS", "2022",
                "キャロウェイ ROGUE ST MAX LS ドライバー", ["roguestmaxls"], []),
    DriverModel("cw_roguestmaxfast", "キャロウェイ", "ROGUE ST MAX FAST", "2022",
                "キャロウェイ ROGUE ST MAX FAST ドライバー", ["roguestmaxfast"], []),
    # --- PARADYM (2023) ---
    DriverModel("cw_paradym", "キャロウェイ", "PARADYM", "2023",
                "キャロウェイ パラダイム ドライバー", ["paradym"],
                ["paradymx", "smoke", "◆", "triplediamond"]),
    DriverModel("cw_paradymx", "キャロウェイ", "PARADYM X", "2023",
                "キャロウェイ パラダイム X ドライバー", ["paradymx"], ["smoke"]),
    DriverModel("cw_paradym_td", "キャロウェイ", "PARADYM ◆◆◆", "2023",
                "キャロウェイ パラダイム トリプルダイヤモンド ドライバー",
                ["paradym", "◆◆◆"], ["smoke", "◆◆◆max"]),
    # --- PARADYM Ai SMOKE (2024) ---
    DriverModel("cw_aismoke_max", "キャロウェイ", "PARADYM Ai SMOKE MAX", "2024",
                "キャロウェイ パラダイム Ai SMOKE MAX ドライバー", ["aismoke", "max"],
                ["maxd", "maxfast", "fast", "◆", "triplediamond", "mini", "340"]),
    DriverModel("cw_aismoke_maxd", "キャロウェイ", "PARADYM Ai SMOKE MAX D", "2024",
                "キャロウェイ パラダイム Ai SMOKE MAX D ドライバー", ["aismoke", "maxd"], ["◆"]),
    DriverModel("cw_aismoke_maxfast", "キャロウェイ", "PARADYM Ai SMOKE MAX FAST", "2024",
                "キャロウェイ パラダイム Ai SMOKE MAX FAST ドライバー", ["aismoke", "maxfast"], []),
    DriverModel("cw_aismoke_td", "キャロウェイ", "PARADYM Ai SMOKE ◆◆◆", "2024",
                "キャロウェイ パラダイム Ai SMOKE トリプルダイヤモンド ドライバー",
                ["aismoke", "◆◆◆"], ["◆◆◆max"]),
    DriverModel("cw_aismoke_tdmax", "キャロウェイ", "PARADYM Ai SMOKE ◆◆◆ MAX", "2024",
                "キャロウェイ パラダイム Ai SMOKE ◆◆◆ MAX ドライバー", ["aismoke", "◆◆◆max"], []),

    # ============ ピン ============
    # --- G425 (2021) ---
    DriverModel("ping_g425max", "ピン", "G425 MAX", "2021",
                "ピン G425 MAX ドライバー", ["g425max"], []),
    DriverModel("ping_g425lst", "ピン", "G425 LST", "2021",
                "ピン G425 LST ドライバー", ["g425lst"], []),
    DriverModel("ping_g425sft", "ピン", "G425 SFT", "2021",
                "ピン G425 SFT ドライバー", ["g425sft"], []),
    # --- G430 (2023) ---
    DriverModel("ping_g430max", "ピン", "G430 MAX", "2023",
                "ピン G430 MAX ドライバー", ["g430max"], ["10k"]),
    DriverModel("ping_g430lst", "ピン", "G430 LST", "2023",
                "ピン G430 LST ドライバー", ["g430lst"], []),
    DriverModel("ping_g430sft", "ピン", "G430 SFT", "2023",
                "ピン G430 SFT ドライバー", ["g430sft"], []),
    # --- G440 (2024) ---
    DriverModel("ping_g440max", "ピン", "G440 MAX", "2024",
                "ピン G440 MAX ドライバー", ["g440max"], ["10k"]),
    DriverModel("ping_g440lst", "ピン", "G440 LST", "2024",
                "ピン G440 LST ドライバー", ["g440lst"], []),
    DriverModel("ping_g440sft", "ピン", "G440 SFT", "2024",
                "ピン G440 SFT ドライバー", ["g440sft"], []),
    # --- G410 (2019) ※写真より ---
    DriverModel("ping_g410plus", "ピン", "G410 PLUS", "2019",
                "ピン G410 PLUS ドライバー", ["g410plus"], []),
    DriverModel("ping_g410lst", "ピン", "G410 LST", "2019",
                "ピン G410 LST ドライバー", ["g410lst"], []),
    DriverModel("ping_g410sft", "ピン", "G410 SFT", "2019",
                "ピン G410 SFT ドライバー", ["g410sft"], []),

    # ============ キャロウェイ EPIC（2021）※写真より ============
    DriverModel("cw_epicspeed", "キャロウェイ", "EPIC SPEED", "2021",
                "キャロウェイ EPIC SPEED ドライバー", ["epicspeed"], []),
    DriverModel("cw_epicmax", "キャロウェイ", "EPIC MAX", "2021",
                "キャロウェイ EPIC MAX ドライバー", ["epicmax"], ["epicmaxls", "fast"]),
    DriverModel("cw_epicmaxls", "キャロウェイ", "EPIC MAX LS", "2021",
                "キャロウェイ EPIC MAX LS ドライバー", ["epicmaxls"], []),

    # ============ タイトリスト ※写真(TS2/TSi3)＋主要 ============
    DriverModel("ti_ts2", "タイトリスト", "TS2", "2018",
                "タイトリスト TS2 ドライバー", ["タイトリスト|titleist", "ts2"], ["tsi2", "tsr2"]),
    DriverModel("ti_tsi2", "タイトリスト", "TSi2", "2021",
                "タイトリスト TSi2 ドライバー", ["tsi2"], []),
    DriverModel("ti_tsi3", "タイトリスト", "TSi3", "2021",
                "タイトリスト TSi3 ドライバー", ["tsi3"], []),
    DriverModel("ti_tsr2", "タイトリスト", "TSR2", "2022",
                "タイトリスト TSR2 ドライバー", ["tsr2"], []),
    DriverModel("ti_tsr3", "タイトリスト", "TSR3", "2022",
                "タイトリスト TSR3 ドライバー", ["tsr3"], []),
    DriverModel("ti_gt2", "タイトリスト", "GT2", "2024",
                "タイトリスト GT2 ドライバー", ["タイトリスト|titleist", "gt2"], []),
    DriverModel("ti_gt3", "タイトリスト", "GT3", "2024",
                "タイトリスト GT3 ドライバー", ["タイトリスト|titleist", "gt3"], []),

    # ============ ダンロップ スリクソン ZX ============
    DriverModel("sx_zx5", "スリクソン", "ZX5", "2021",
                "スリクソン ZX5 ドライバー", ["zx5"], ["mk"]),
    DriverModel("sx_zx7", "スリクソン", "ZX7", "2021",
                "スリクソン ZX7 ドライバー", ["zx7"], ["mk"]),
    DriverModel("sx_zx5mk2", "スリクソン", "ZX5 MkII", "2023",
                "スリクソン ZX5 MkII ドライバー", ["zx5mk"], []),
    DriverModel("sx_zx7mk2", "スリクソン", "ZX7 MkII", "2023",
                "スリクソン ZX7 MkII ドライバー", ["zx7mk"], []),

    # ============ ダンロップ ゼクシオ ============
    DriverModel("xx_xxio12", "ゼクシオ", "ゼクシオ12", "2021",
                "ゼクシオ12 ドライバー", ["xxio12|ゼクシオ12"], []),
    DriverModel("xx_xxio13", "ゼクシオ", "ゼクシオ13", "2023",
                "ゼクシオ13 ドライバー", ["xxio13|ゼクシオ13"], []),

    # ============ コブラ ============
    DriverModel("cb_radspeed", "コブラ", "RADSPEED", "2021",
                "コブラ RADSPEED ドライバー", ["radspeed"], ["radspeedxb", "radspeedxd"]),
    DriverModel("cb_radspeedxb", "コブラ", "RADSPEED XB", "2021",
                "コブラ RADSPEED XB ドライバー", ["radspeedxb"], []),
    DriverModel("cb_radspeedxd", "コブラ", "RADSPEED XD", "2021",
                "コブラ RADSPEED XD ドライバー", ["radspeedxd"], []),
    DriverModel("cb_ltdx", "コブラ", "KING LTDx", "2022",
                "コブラ KING LTDx ドライバー", ["ltdx"], ["ltdxls", "ltdxmax"]),
    DriverModel("cb_ltdxls", "コブラ", "KING LTDx LS", "2022",
                "コブラ KING LTDx LS ドライバー", ["ltdxls"], []),
    DriverModel("cb_ltdxmax", "コブラ", "KING LTDx MAX", "2022",
                "コブラ KING LTDx MAX ドライバー", ["ltdxmax"], []),
    DriverModel("cb_aerojet", "コブラ", "AEROJET", "2023",
                "コブラ AEROJET ドライバー", ["aerojet"], ["aerojetls", "aerojetmax"]),
    DriverModel("cb_aerojetls", "コブラ", "AEROJET LS", "2023",
                "コブラ AEROJET LS ドライバー", ["aerojetls"], []),
    DriverModel("cb_aerojetmax", "コブラ", "AEROJET MAX", "2023",
                "コブラ AEROJET MAX ドライバー", ["aerojetmax"], []),
    DriverModel("cb_darkspeed", "コブラ", "DARKSPEED", "2024",
                "コブラ DARKSPEED ドライバー", ["darkspeed"], ["darkspeedls", "darkspeedmax", "darkspeedx"]),
    DriverModel("cb_darkspeedls", "コブラ", "DARKSPEED LS", "2024",
                "コブラ DARKSPEED LS ドライバー", ["darkspeedls"], []),
    DriverModel("cb_darkspeedmax", "コブラ", "DARKSPEED MAX", "2024",
                "コブラ DARKSPEED MAX ドライバー", ["darkspeedmax"], []),
    DriverModel("cb_darkspeedx", "コブラ", "DARKSPEED X", "2024",
                "コブラ DARKSPEED X ドライバー", ["darkspeedx"], []),

    # ============ ミズノ ST ============
    DriverModel("mz_stz", "ミズノ", "ST-Z", "2021",
                "ミズノ ST-Z ドライバー", ["ミズノ|mizuno", "stz"], ["stz220", "stz230"]),
    DriverModel("mz_stx", "ミズノ", "ST-X", "2021",
                "ミズノ ST-X ドライバー", ["ミズノ|mizuno", "stx"], ["stx220", "stx230"]),
    DriverModel("mz_stz220", "ミズノ", "ST-Z 220", "2022",
                "ミズノ ST-Z 220 ドライバー", ["stz220"], []),
    DriverModel("mz_stx220", "ミズノ", "ST-X 220", "2022",
                "ミズノ ST-X 220 ドライバー", ["stx220"], []),
    DriverModel("mz_stz230", "ミズノ", "ST-Z 230", "2023",
                "ミズノ ST-Z 230 ドライバー", ["stz230"], []),
    DriverModel("mz_stx230", "ミズノ", "ST-X 230", "2023",
                "ミズノ ST-X 230 ドライバー", ["stx230"], []),
    DriverModel("mz_stmax230", "ミズノ", "ST-MAX 230", "2023",
                "ミズノ ST-MAX 230 ドライバー", ["stmax230"], []),

    # ============ プロギア PRGR ============
    DriverModel("pr_rs5", "プロギア", "RS5", "2022",
                "プロギア RS5 ドライバー", ["プロギア|prgr", "rs5"], []),
    DriverModel("pr_rsjust", "プロギア", "RS JUST", "2023",
                "プロギア RS JUST ドライバー", ["rsjust"], []),

    # ============ ヤマハ ※写真より ============
    DriverModel("ym_rmxvd59", "ヤマハ", "RMX VD59", "2023",
                "ヤマハ RMX VD59 ドライバー", ["vd59"], []),
    DriverModel("ym_rmxvd40", "ヤマハ", "RMX VD40", "2023",
                "ヤマハ RMX VD40 ドライバー", ["vd40"], []),
    DriverModel("ym_inpresud2", "ヤマハ", "inpres UD+2", "2021",
                "ヤマハ インプレス UD+2 ドライバー", ["ud+2"], []),
    DriverModel("ym_drivestar", "ヤマハ", "inpres DRIVESTAR", "2022",
                "ヤマハ インプレス ドライブスター ドライバー", ["drivestar|ドライブスター"], []),

    # ============ 本間 HONMA ※写真より ============
    DriverModel("hm_twgs", "本間", "TOUR WORLD GS", "2022",
                "本間 ツアーワールド GS ドライバー", ["本間|ホンマ|honma", "gs"], []),
    DriverModel("hm_tw757", "本間", "TW757", "2022",
                "本間 TW757 ドライバー", ["tw757"], []),

    # ============ NEXGEN（ゴルフパートナー）※写真より ============
    DriverModel("nx_ns210", "NEXGEN", "NEXGEN NS210", "2022",
                "NEXGEN NS210 ドライバー", ["ns210"], []),
    DriverModel("nx_ns220", "NEXGEN", "NEXGEN NS220", "2023",
                "NEXGEN NS220 ドライバー", ["ns220"], []),
    DriverModel("nx_type460", "NEXGEN", "NEXGEN TYPE-460", "2019",
                "NEXGEN TYPE-460 ドライバー", ["type460|タイプ460"], []),

    # ============ PXG ※指定より ============
    DriverModel("pxg_blackops", "PXG", "0311 BLACK OPS", "2024",
                "PXG 0311 ブラックオプス ドライバー", ["blackops|ブラックオプス"], []),

    # ============ 地クラブ・その他 ※指定より ============
    DriverModel("fuso_dream_ks2", "フソードリーム", "FUSO DREAM KS2", "—",
                "フソー ドリーム KS2 ドライバー", ["ks2", "ドリーム|dream|フソー|fuso"], []),

    # ==================== フェアウェイウッド ====================
    DriverModel("fw_tm_sim2max", "テーラーメイド", "SIM2 MAX", "2021",
                "テーラーメイド SIM2 MAX フェアウェイウッド", ["sim2max"], ["maxd"], category="fw"),
    DriverModel("fw_tm_stealth2", "テーラーメイド", "STEALTH2", "2023",
                "テーラーメイド ステルス2 フェアウェイウッド", ["stealth2"], ["plus", "hd"], category="fw"),
    DriverModel("fw_tm_qi10", "テーラーメイド", "Qi10", "2024",
                "テーラーメイド Qi10 フェアウェイウッド", ["qi10"], ["max"], category="fw"),
    DriverModel("fw_cw_paradym", "キャロウェイ", "PARADYM", "2023",
                "キャロウェイ パラダイム フェアウェイウッド", ["paradym"], ["smoke", "x"], category="fw"),
    DriverModel("fw_cw_aismoke", "キャロウェイ", "PARADYM Ai SMOKE", "2024",
                "キャロウェイ パラダイム Ai SMOKE フェアウェイウッド", ["aismoke"], [], category="fw"),
    DriverModel("fw_ping_g425max", "ピン", "G425 MAX", "2021",
                "ピン G425 MAX フェアウェイウッド", ["g425"], [], category="fw"),
    DriverModel("fw_ping_g430max", "ピン", "G430", "2023",
                "ピン G430 フェアウェイウッド", ["g430"], [], category="fw"),
    DriverModel("fw_ping_g440", "ピン", "G440", "2024",
                "ピン G440 フェアウェイウッド", ["g440"], [], category="fw"),
    DriverModel("fw_sx_zx", "スリクソン", "ZX", "2021",
                "スリクソン ZX フェアウェイウッド", ["スリクソン|srixon", "zx"], [], category="fw"),
    DriverModel("fw_xx_xxio12", "ゼクシオ", "ゼクシオ12", "2021",
                "ゼクシオ12 フェアウェイウッド", ["xxio12|ゼクシオ12"], [], category="fw"),
    DriverModel("fw_cb_aerojet", "コブラ", "AEROJET", "2023",
                "コブラ AEROJET フェアウェイウッド", ["aerojet"], [], category="fw"),
    DriverModel("fw_cb_darkspeed", "コブラ", "DARKSPEED", "2024",
                "コブラ DARKSPEED フェアウェイウッド", ["darkspeed"], [], category="fw"),
    DriverModel("fw_mz_st", "ミズノ", "ST-Z/X", "2022",
                "ミズノ ST フェアウェイウッド", ["ミズノ|mizuno", "st"], [], category="fw"),
    DriverModel("fw_ti_tsr", "タイトリスト", "TSR", "2022",
                "タイトリスト TSR フェアウェイウッド", ["tsr"], [], category="fw"),

    # ==================== ユーティリティ ====================
    DriverModel("ut_tm_sim2max", "テーラーメイド", "SIM2 MAX レスキュー", "2021",
                "テーラーメイド SIM2 MAX レスキュー ユーティリティ", ["sim2max"], [], category="ut"),
    DriverModel("ut_tm_stealth2", "テーラーメイド", "STEALTH2 レスキュー", "2023",
                "テーラーメイド ステルス2 レスキュー ユーティリティ", ["stealth2"], [], category="ut"),
    DriverModel("ut_tm_qi10", "テーラーメイド", "Qi10 レスキュー", "2024",
                "テーラーメイド Qi10 レスキュー ユーティリティ", ["qi10"], [], category="ut"),
    DriverModel("ut_cw_paradym", "キャロウェイ", "PARADYM UT", "2023",
                "キャロウェイ パラダイム ユーティリティ", ["paradym"], ["smoke"], category="ut"),
    DriverModel("ut_cw_aismoke", "キャロウェイ", "Ai SMOKE UT", "2024",
                "キャロウェイ パラダイム Ai SMOKE ユーティリティ", ["aismoke"], [], category="ut"),
    DriverModel("ut_ping_g425", "ピン", "G425 ハイブリッド", "2021",
                "ピン G425 ハイブリッド ユーティリティ", ["g425"], [], category="ut"),
    DriverModel("ut_ping_g430", "ピン", "G430 ハイブリッド", "2023",
                "ピン G430 ハイブリッド ユーティリティ", ["g430"], [], category="ut"),
    DriverModel("ut_sx_zx", "スリクソン", "ZX ユーティリティ", "2021",
                "スリクソン ZX ユーティリティ", ["スリクソン|srixon", "zx"], [], category="ut"),
    DriverModel("ut_xx_xxio12", "ゼクシオ", "ゼクシオ12 UT", "2021",
                "ゼクシオ12 ユーティリティ", ["xxio12|ゼクシオ12"], [], category="ut"),
    DriverModel("ut_mz_flihi", "ミズノ", "Fli-Hi / ST UT", "2022",
                "ミズノ ユーティリティ", ["ミズノ|mizuno", "st|flihi"], [], category="ut"),
    DriverModel("ut_ti_tsr", "タイトリスト", "TSR ユーティリティ", "2022",
                "タイトリスト TSR ユーティリティ", ["tsr"], [], category="ut"),

    # ==================== アイアン ====================
    DriverModel("ir_tm_p790", "テーラーメイド", "P790", "2023",
                "テーラーメイド P790 アイアン", ["p790"], [], category="iron"),
    DriverModel("ir_tm_stealth", "テーラーメイド", "STEALTH アイアン", "2022",
                "テーラーメイド ステルス アイアン", ["stealth"], ["stealth2", "hd"], category="iron"),
    DriverModel("ir_tm_qi", "テーラーメイド", "Qi アイアン", "2024",
                "テーラーメイド Qi10 アイアン", ["qi"], [], category="iron"),
    DriverModel("ir_cw_apex", "キャロウェイ", "APEX", "2021",
                "キャロウェイ APEX アイアン", ["キャロウェイ|callaway", "apex"],
                ["apexpro", "apextcb", "apexmb", "apexdcb", "apexcb"], category="iron"),
    DriverModel("ir_cw_paradym", "キャロウェイ", "PARADYM アイアン", "2023",
                "キャロウェイ パラダイム アイアン", ["paradym"], ["smoke"], category="iron"),
    DriverModel("ir_cw_aismoke", "キャロウェイ", "Ai SMOKE アイアン", "2024",
                "キャロウェイ パラダイム Ai SMOKE アイアン", ["aismoke|ai"], [], category="iron"),
    DriverModel("ir_ping_i525", "ピン", "i525", "2022",
                "ピン i525 アイアン", ["i525"], [], category="iron"),
    DriverModel("ir_ping_i230", "ピン", "i230", "2023",
                "ピン i230 アイアン", ["i230"], [], category="iron"),
    DriverModel("ir_ping_g430", "ピン", "G430 アイアン", "2023",
                "ピン G430 アイアン", ["g430"], [], category="iron"),
    DriverModel("ir_ti_t100", "タイトリスト", "T100", "2023",
                "タイトリスト T100 アイアン", ["t100"], ["t100s"], category="iron"),
    DriverModel("ir_ti_t200", "タイトリスト", "T200", "2023",
                "タイトリスト T200 アイアン", ["t200"], [], category="iron"),
    DriverModel("ir_sx_zx5", "スリクソン", "ZX5 アイアン", "2021",
                "スリクソン ZX5 アイアン", ["zx5"], ["mk"], category="iron"),
    DriverModel("ir_sx_zx5mk2", "スリクソン", "ZX5 MkII アイアン", "2023",
                "スリクソン ZX5 MkII アイアン", ["zx5mk"], [], category="iron"),
    DriverModel("ir_mz_jpx923", "ミズノ", "JPX923", "2022",
                "ミズノ JPX923 アイアン", ["jpx923"], [], category="iron"),
    DriverModel("ir_mz_jpx925", "ミズノ", "JPX925", "2024",
                "ミズノ JPX925 アイアン", ["jpx925"], [], category="iron"),
    DriverModel("ir_mz_pro", "ミズノ", "Pro 241/243/245", "2023",
                "ミズノ Pro アイアン", ["ミズノ|mizuno", "pro24"], [], category="iron"),

    # ============================================================
    #  名機（〜2020・今も人気/リセール良好）  ※ '=' は単語境界マッチ
    # ============================================================
    # --- 名機ドライバー：テーラーメイド ---
    DriverModel("tm_sim", "テーラーメイド", "SIM", "2020",
                "テーラーメイド SIM ドライバー", ["テーラーメイド|taylormade", "=sim"],
                ["max", "グローレ|gloire"]),
    DriverModel("tm_simmax", "テーラーメイド", "SIM MAX", "2020",
                "テーラーメイド SIM MAX ドライバー", ["simmax"], ["maxd"]),
    DriverModel("tm_simmaxd", "テーラーメイド", "SIM MAX-D", "2020",
                "テーラーメイド SIM MAX-D ドライバー", ["simmaxd"], []),
    DriverModel("tm_m6", "テーラーメイド", "M6", "2019",
                "テーラーメイド M6 ドライバー", ["テーラーメイド|taylormade", "=m6"], []),
    DriverModel("tm_m5", "テーラーメイド", "M5", "2019",
                "テーラーメイド M5 ドライバー", ["テーラーメイド|taylormade", "=m5"], []),
    DriverModel("tm_m4", "テーラーメイド", "M4", "2018",
                "テーラーメイド M4 ドライバー", ["テーラーメイド|taylormade", "=m4"], []),
    DriverModel("tm_m3", "テーラーメイド", "M3", "2018",
                "テーラーメイド M3 ドライバー", ["テーラーメイド|taylormade", "=m3"], []),
    DriverModel("tm_m2d", "テーラーメイド", "M2", "2016",
                "テーラーメイド M2 ドライバー", ["テーラーメイド|taylormade", "=m2"], []),
    DriverModel("tm_m1d", "テーラーメイド", "M1", "2016",
                "テーラーメイド M1 ドライバー", ["テーラーメイド|taylormade", "=m1"], []),
    # --- 名機ドライバー：キャロウェイ ---
    DriverModel("cw_mavrik", "キャロウェイ", "MAVRIK", "2020",
                "キャロウェイ MAVRIK ドライバー", ["mavrik"], ["max", "subzero", "sub"]),
    DriverModel("cw_mavrikmax", "キャロウェイ", "MAVRIK MAX", "2020",
                "キャロウェイ MAVRIK MAX ドライバー", ["mavrikmax"], []),
    DriverModel("cw_mavriksz", "キャロウェイ", "MAVRIK SUB ZERO", "2020",
                "キャロウェイ MAVRIK サブゼロ ドライバー", ["mavrik", "subzero|sub"], []),
    DriverModel("cw_epicflash", "キャロウェイ", "EPIC FLASH", "2019",
                "キャロウェイ EPIC FLASH ドライバー", ["epicflash"], ["subzero", "sub"]),
    DriverModel("cw_epicflashsz", "キャロウェイ", "EPIC FLASH SUB ZERO", "2019",
                "キャロウェイ EPIC FLASH サブゼロ ドライバー", ["epicflash", "subzero|sub"], []),
    DriverModel("cw_rogue", "キャロウェイ", "ROGUE", "2018",
                "キャロウェイ ROGUE ドライバー", ["rogue"], ["roguest", "subzero", "sub", "star"]),
    DriverModel("cw_roguesz", "キャロウェイ", "ROGUE SUB ZERO", "2018",
                "キャロウェイ ROGUE サブゼロ ドライバー", ["rogue", "subzero|sub"], ["roguest"]),
    # --- 名機ドライバー：ピン ---
    DriverModel("ping_g400", "ピン", "G400", "2017",
                "ピン G400 ドライバー", ["g400"], ["max", "lst", "sft"]),
    DriverModel("ping_g400max", "ピン", "G400 MAX", "2018",
                "ピン G400 MAX ドライバー", ["g400max"], []),
    DriverModel("ping_g400lst", "ピン", "G400 LST", "2017",
                "ピン G400 LST ドライバー", ["g400lst"], []),
    DriverModel("ping_g400sft", "ピン", "G400 SFT", "2017",
                "ピン G400 SFT ドライバー", ["g400sft"], []),
    DriverModel("ping_g30", "ピン", "G30", "2014",
                "ピン G30 ドライバー", ["ピン|ping", "g30"], ["g300", "g30lstec"]),
    # --- 名機ドライバー：タイトリスト ---
    DriverModel("ti_ts3", "タイトリスト", "TS3", "2018",
                "タイトリスト TS3 ドライバー", ["ts3"], ["tsi3", "tsr3"]),
    DriverModel("ti_917", "タイトリスト", "917 D2/D3", "2016",
                "タイトリスト 917 ドライバー", ["タイトリスト|titleist", "=917"], []),
    DriverModel("ti_915", "タイトリスト", "915 D2/D3", "2015",
                "タイトリスト 915 ドライバー", ["タイトリスト|titleist", "=915"], []),
    # --- 名機ドライバー：ミズノ/コブラ/スリクソン ---
    DriverModel("mz_st200", "ミズノ", "ST200", "2020",
                "ミズノ ST200 ドライバー", ["st200"], ["st200g", "st200x"]),
    DriverModel("mz_st200x", "ミズノ", "ST200X", "2020",
                "ミズノ ST200X ドライバー", ["st200x"], []),
    DriverModel("cb_speedzone", "コブラ", "KING SPEEDZONE", "2020",
                "コブラ KING SPEEDZONE ドライバー", ["speedzone"], ["xb", "extreme"]),
    DriverModel("cb_f9", "コブラ", "KING F9", "2019",
                "コブラ KING F9 ドライバー", ["コブラ|cobra", "=f9"], []),
    DriverModel("cb_f8", "コブラ", "KING F8", "2018",
                "コブラ KING F8 ドライバー", ["コブラ|cobra", "=f8"], []),
    DriverModel("sx_z565d", "スリクソン", "Z565", "2016",
                "スリクソン Z565 ドライバー", ["z565"], []),
    DriverModel("sx_z585d", "スリクソン", "Z585", "2018",
                "スリクソン Z585 ドライバー", ["z585"], []),

    # --- 名機アイアン：スリクソン Zシリーズ ---
    DriverModel("ir_sx_z525", "スリクソン", "Z525", "2012",
                "スリクソン Z525 アイアン", ["z525"], [], category="iron"),
    DriverModel("ir_sx_z725", "スリクソン", "Z725", "2012",
                "スリクソン Z725 アイアン", ["z725"], [], category="iron"),
    DriverModel("ir_sx_z925", "スリクソン", "Z925", "2012",
                "スリクソン Z925 アイアン", ["z925"], [], category="iron"),
    DriverModel("ir_sx_z545", "スリクソン", "Z545", "2014",
                "スリクソン Z545 アイアン", ["z545"], [], category="iron"),
    DriverModel("ir_sx_z745", "スリクソン", "Z745", "2014",
                "スリクソン Z745 アイアン", ["z745"], [], category="iron"),
    DriverModel("ir_sx_z565", "スリクソン", "Z565", "2016",
                "スリクソン Z565 アイアン", ["z565"], [], category="iron"),
    DriverModel("ir_sx_z765", "スリクソン", "Z765", "2016",
                "スリクソン Z765 アイアン", ["z765"], [], category="iron"),
    DriverModel("ir_sx_z585", "スリクソン", "Z585", "2018",
                "スリクソン Z585 アイアン", ["z585"], [], category="iron"),
    DriverModel("ir_sx_z785", "スリクソン", "Z785", "2018",
                "スリクソン Z785 アイアン", ["z785"], [], category="iron"),
    DriverModel("ir_sx_zx7", "スリクソン", "ZX7", "2021",
                "スリクソン ZX7 アイアン", ["zx7"], ["mk"], category="iron"),
    # --- 名機アイアン：ピン ---
    DriverModel("ir_ping_i210", "ピン", "i210", "2018",
                "ピン i210 アイアン", ["i210"], [], category="iron"),
    DriverModel("ir_ping_i200", "ピン", "i200", "2017",
                "ピン i200 アイアン", ["i200"], [], category="iron"),
    DriverModel("ir_ping_i500", "ピン", "i500", "2018",
                "ピン i500 アイアン", ["i500"], [], category="iron"),
    DriverModel("ir_ping_iblade", "ピン", "iBlade", "2016",
                "ピン iBlade アイアン", ["iblade"], [], category="iron"),
    DriverModel("ir_ping_blueprint", "ピン", "Blueprint", "2019",
                "ピン Blueprint アイアン", ["blueprint"], [], category="iron"),
    DriverModel("ir_ping_g700", "ピン", "G700", "2018",
                "ピン G700 アイアン", ["ピン|ping", "g700"], [], category="iron"),
    DriverModel("ir_ping_i59", "ピン", "i59", "2021",
                "ピン i59 アイアン", ["i59"], [], category="iron"),
    # --- 名機アイアン：タイトリスト AP2 ---
    DriverModel("ir_ti_ap2_716", "タイトリスト", "716 AP2", "2016",
                "タイトリスト 716 AP2 アイアン", ["=716", "ap2"], [], category="iron"),
    DriverModel("ir_ti_ap2_718", "タイトリスト", "718 AP2", "2018",
                "タイトリスト 718 AP2 アイアン", ["=718", "ap2"], [], category="iron"),
    DriverModel("ir_ti_ap2_714", "タイトリスト", "714 AP2", "2014",
                "タイトリスト 714 AP2 アイアン", ["=714", "ap2"], [], category="iron"),
    # --- 名機アイアン：テーラーメイド ---
    DriverModel("ir_tm_p770", "テーラーメイド", "P770", "2020",
                "テーラーメイド P770 アイアン", ["p770"], [], category="iron"),
    DriverModel("ir_tm_p730", "テーラーメイド", "P730", "2017",
                "テーラーメイド P730 アイアン", ["p730"], [], category="iron"),
    DriverModel("ir_tm_p7mc", "テーラーメイド", "P7MC", "2020",
                "テーラーメイド P7MC アイアン", ["p7mc"], [], category="iron"),
    DriverModel("ir_tm_simmax", "テーラーメイド", "SIM MAX アイアン", "2020",
                "テーラーメイド SIM MAX アイアン", ["simmax"], [], category="iron"),
    DriverModel("ir_tm_m2", "テーラーメイド", "M2 アイアン", "2017",
                "テーラーメイド M2 アイアン", ["テーラーメイド|taylormade", "=m2"], [], category="iron"),
    # --- 名機アイアン：キャロウェイ ---
    DriverModel("ir_cw_apexpro", "キャロウェイ", "APEX PRO", "2019",
                "キャロウェイ APEX PRO アイアン", ["apexpro"], [], category="iron"),
    DriverModel("ir_cw_rogue", "キャロウェイ", "ROGUE アイアン", "2018",
                "キャロウェイ ROGUE アイアン", ["rogue"], ["roguest", "smoke"], category="iron"),
    DriverModel("ir_cw_xforged", "キャロウェイ", "X FORGED", "2018",
                "キャロウェイ X FORGED アイアン", ["xforged"], [], category="iron"),
    DriverModel("ir_cw_mavrik", "キャロウェイ", "MAVRIK アイアン", "2020",
                "キャロウェイ MAVRIK アイアン", ["mavrik"], [], category="iron"),
    # --- 名機アイアン：ミズノ ---
    DriverModel("ir_mz_jpx919", "ミズノ", "JPX919", "2019",
                "ミズノ JPX919 アイアン", ["jpx919"], [], category="iron"),
    DriverModel("ir_mz_jpx900", "ミズノ", "JPX900", "2016",
                "ミズノ JPX900 アイアン", ["jpx900"], [], category="iron"),
    DriverModel("ir_mz_mp20", "ミズノ", "MP-20", "2019",
                "ミズノ MP-20 アイアン", ["ミズノ|mizuno", "mp20"], [], category="iron"),
    DriverModel("ir_mz_mp18", "ミズノ", "MP-18", "2017",
                "ミズノ MP-18 アイアン", ["ミズノ|mizuno", "mp18"], [], category="iron"),
    DriverModel("ir_mz_pro22", "ミズノ", "Pro 221/223/225", "2021",
                "ミズノ Pro 223 アイアン", ["ミズノ|mizuno", "pro22"], [], category="iron"),

    # ============ 2021〜2024 アイアン 追加（主要メーカー兄弟機・残り） ============
    # テーラーメイド
    DriverModel("ir_tm_sim2max", "テーラーメイド", "SIM2 MAX アイアン", "2021",
                "テーラーメイド SIM2 MAX アイアン", ["sim2max"], [], category="iron"),
    DriverModel("ir_tm_p7mb", "テーラーメイド", "P7MB", "2023",
                "テーラーメイド P7MB アイアン", ["p7mb"], [], category="iron"),
    # キャロウェイ
    DriverModel("ir_cw_roguestmax", "キャロウェイ", "ROGUE ST MAX アイアン", "2022",
                "キャロウェイ ROGUE ST MAX アイアン", ["roguestmax"], ["os"], category="iron"),
    DriverModel("ir_cw_roguestmaxos", "キャロウェイ", "ROGUE ST MAX OS アイアン", "2022",
                "キャロウェイ ROGUE ST MAX OS アイアン", ["roguestmax", "os"], [], category="iron"),
    DriverModel("ir_cw_apexdcb", "キャロウェイ", "APEX DCB", "2021",
                "キャロウェイ APEX DCB アイアン", ["apexdcb"], [], category="iron"),
    DriverModel("ir_cw_apextcb", "キャロウェイ", "APEX TCB", "2021",
                "キャロウェイ APEX TCB アイアン", ["apextcb"], [], category="iron"),
    DriverModel("ir_cw_bigbertha", "キャロウェイ", "BIG BERTHA アイアン", "2023",
                "キャロウェイ ビッグバーサ アイアン", ["bigbertha|ビッグバーサ"], [], category="iron"),
    # ピン
    DriverModel("ir_ping_g425", "ピン", "G425 アイアン", "2021",
                "ピン G425 アイアン", ["g425"], [], category="iron"),
    DriverModel("ir_ping_g440", "ピン", "G440 アイアン", "2024",
                "ピン G440 アイアン", ["g440"], [], category="iron"),
    # タイトリスト
    DriverModel("ir_ti_t300", "タイトリスト", "T300", "2023",
                "タイトリスト T300 アイアン", ["t300"], [], category="iron"),
    DriverModel("ir_ti_t350", "タイトリスト", "T350", "2023",
                "タイトリスト T350 アイアン", ["t350"], [], category="iron"),
    DriverModel("ir_ti_t100s", "タイトリスト", "T100S", "2021",
                "タイトリスト T100S アイアン", ["t100s"], [], category="iron"),
    # ミズノ
    DriverModel("ir_mz_jpx921", "ミズノ", "JPX921", "2021",
                "ミズノ JPX921 アイアン", ["jpx921"], [], category="iron"),
    # スリクソン
    DriverModel("ir_sx_zx4", "スリクソン", "ZX4", "2021",
                "スリクソン ZX4 アイアン", ["zx4"], ["mk"], category="iron"),
    DriverModel("ir_sx_zx7mk2", "スリクソン", "ZX7 MkII", "2023",
                "スリクソン ZX7 MkII アイアン", ["zx7mk"], [], category="iron"),
    DriverModel("ir_sx_zx4mk2", "スリクソン", "ZX4 MkII", "2023",
                "スリクソン ZX4 MkII アイアン", ["zx4mk"], [], category="iron"),
    # コブラ
    DriverModel("ir_cb_radspeed", "コブラ", "RADSPEED アイアン", "2021",
                "コブラ RADSPEED アイアン", ["radspeed"], [], category="iron"),
    DriverModel("ir_cb_ltdx", "コブラ", "KING LTDx アイアン", "2022",
                "コブラ KING LTDx アイアン", ["ltdx"], [], category="iron"),
    DriverModel("ir_cb_aerojet", "コブラ", "AEROJET アイアン", "2023",
                "コブラ AEROJET アイアン", ["aerojet"], [], category="iron"),
    DriverModel("ir_cb_darkspeed", "コブラ", "DARKSPEED アイアン", "2024",
                "コブラ DARKSPEED アイアン", ["darkspeed"], [], category="iron"),

    # ============ 飛び系アイアン（7番≒27°以下の強ロフト・高反発系） ============
    # 海外メジャーの飛び系
    DriverModel("ir_ping_g710", "ピン", "G710", "2020",
                "ピン G710 アイアン", ["g710"], [], category="iron"),
    DriverModel("ir_ping_g730", "ピン", "G730", "2024",
                "ピン G730 アイアン", ["g730"], [], category="iron"),
    DriverModel("ir_ti_t400", "タイトリスト", "T400", "2021",
                "タイトリスト T400 アイアン", ["t400"], [], category="iron"),
    DriverModel("ir_tm_stealthhd", "テーラーメイド", "STEALTH HD アイアン", "2022",
                "テーラーメイド ステルス HD アイアン", ["stealthhd"], [], category="iron"),
    # 国産の飛び系（王道）
    DriverModel("ir_ym_ud2", "ヤマハ", "inpres UD+2 アイアン", "2021",
                "ヤマハ インプレス UD+2 アイアン", ["ud+2"], [], category="iron"),
    DriverModel("ir_xx_xxio12", "ゼクシオ", "ゼクシオ12 アイアン", "2021",
                "ゼクシオ12 アイアン", ["xxio12|ゼクシオ12"], [], category="iron"),
    DriverModel("ir_xx_xxio13", "ゼクシオ", "ゼクシオ13 アイアン", "2023",
                "ゼクシオ13 アイアン", ["xxio13|ゼクシオ13"], [], category="iron"),
    DriverModel("ir_xx_xxiox", "ゼクシオ", "ゼクシオ エックス アイアン", "2022",
                "ゼクシオ エックス アイアン", ["xxiox|ゼクシオエックス|ゼクシオクロス|ゼクシオx"], [], category="iron"),
    DriverModel("ir_pr_egg", "プロギア", "egg アイアン", "—",
                "プロギア egg アイアン", ["プロギア|prgr", "egg"], [], category="iron"),
    DriverModel("ir_hm_d1", "本間", "D1 アイアン", "—",
                "本間 D1 アイアン", ["本間|ホンマ|honma", "=d1"], [], category="iron"),
    DriverModel("ir_onoff_aka", "オノフ", "AKA（赤）アイアン", "—",
                "オノフ AKA 赤 アイアン", ["オノフ|onoff", "aka|赤"], [], category="iron"),
    # 地クラブ・超高反発の飛び系
    DriverModel("ir_works_hisho", "ワークスゴルフ", "マキシマックス飛匠", "—",
                "ワークスゴルフ マキシマックス 飛匠 アイアン", ["飛匠|マキシマックス"], [], category="iron"),
    DriverModel("ir_works_hyperblade", "ワークスゴルフ", "ハイパーブレード", "—",
                "ワークスゴルフ ハイパーブレード アイアン", ["ハイパーブレード|hyperblade"], [], category="iron"),
    DriverModel("ir_katana_voltio", "カタナ", "ボルティオ", "—",
                "カタナ ボルティオ アイアン", ["ボルティオ|voltio"], [], category="iron"),
    DriverModel("ir_dynamics", "ダイナミクス", "Dynamics 高反発", "—",
                "ダイナミクス 高反発 アイアン", ["ダイナミクス|dynamics"], [], category="iron"),
    # ナイキ（指定・旧モデル）
    DriverModel("ir_nike_slingshot", "ナイキ", "Slingshot OSS", "—",
                "ナイキ スリングショット OSS アイアン", ["slingshot|スリングショット"], [], category="iron"),

    # ============ ニッチ・地クラブ・旧名作アイアン（おもしろ枠） ============
    # 海外の旧飛び系
    DriverModel("ir_cw_xr", "キャロウェイ", "XR アイアン", "2015",
                "キャロウェイ XR アイアン", ["キャロウェイ|callaway", "=xr"], [], category="iron"),
    DriverModel("ir_tm_mcgb", "テーラーメイド", "M CGB アイアン", "2017",
                "テーラーメイド M CGB アイアン", ["mcgb"], [], category="iron"),
    DriverModel("ir_cb_fmax", "コブラ", "F-MAX アイアン", "—",
                "コブラ F-MAX アイアン", ["コブラ|cobra", "fmax"], [], category="iron"),
    DriverModel("ir_hm_bezeal", "本間", "BeZEAL アイアン", "—",
                "本間 BeZEAL アイアン", ["bezeal|ビジール"], [], category="iron"),
    DriverModel("ir_ym_rmx", "ヤマハ", "RMX アイアン", "—",
                "ヤマハ RMX アイアン", ["ヤマハ|yamaha", "rmx"], [], category="iron"),
    DriverModel("ir_onoff_kuro", "オノフ", "KURO（黒）アイアン", "—",
                "オノフ KURO 黒 アイアン", ["オノフ|onoff", "kuro|黒"], [], category="iron"),
    # 地クラブ・超高反発（おもしろニッチ）
    DriverModel("ir_grandprix", "グランプリ", "グランプリ 高反発", "—",
                "グランプリ 高反発 アイアン", ["グランプリ|grandprix"], [], category="iron"),
    DriverModel("ir_georgespencer", "ジョージスペンサー", "ジョージスペンサー", "—",
                "ジョージスペンサー アイアン", ["ジョージスペンサー|georgespencer"], [], category="iron"),
    DriverModel("ir_baldo", "バルド", "BALDO", "—",
                "バルド BALDO アイアン", ["バルド|baldo"], [], category="iron"),
    DriverModel("ir_kasco_tornado", "キャスコ", "パワートルネード", "—",
                "キャスコ パワートルネード アイアン", ["パワートルネード|powertornado"], [], category="iron"),
    DriverModel("ir_mutsumi", "ムツミホンマ", "ムツミホンマ 高反発", "—",
                "ムツミホンマ アイアン", ["ムツミホンマ"], [], category="iron"),
    DriverModel("ir_works_onisco", "ワークスゴルフ", "鬼パワー/鬼スコア", "—",
                "ワークスゴルフ 鬼 アイアン", ["鬼スコア|鬼パワー"], [], category="iron"),
    # 名物フォージド・カスタム地クラブ
    DriverModel("ir_baldo_tt", "バルド", "BALDO COMPETIZIONE", "—",
                "バルド コンペチオーネ アイアン", ["コンペチオーネ|competizione"], [], category="iron"),
    DriverModel("ir_docus", "ドゥーカス", "DOCUS", "—",
                "ドゥーカス DOCUS アイアン", ["ドゥーカス|docus"], [], category="iron"),
    DriverModel("ir_masuda", "マスダゴルフ", "マスダゴルフ", "—",
                "マスダゴルフ アイアン", ["マスダゴルフ|masudagolf"], [], category="iron"),
    DriverModel("ir_roddio", "ロッディオ", "RODDIO", "—",
                "ロッディオ RODDIO アイアン", ["ロッディオ|roddio"], [], category="iron"),
    DriverModel("ir_lynx", "リンクス", "リンクス アイアン", "—",
                "リンクス アイアン", ["リンクス|lynx"], [], category="iron"),

    # ============ マーク金井 再生リスト（打たず/買わず）より・クラブのみ ============
    # --- ドライバー ---
    DriverModel("dr_prgr_rsduo", "プロギア", "RS DUO", "2025",
                "プロギア RS DUO ドライバー", ["プロギア|prgr", "rsduo"], []),
    DriverModel("dr_prgr_superegg", "プロギア", "スーパーegg", "—",
                "プロギア スーパーegg ドライバー", ["プロギア|prgr", "スーパーegg|superegg"], []),
    DriverModel("dr_prgr_rsf", "プロギア", "RS-F", "—",
                "プロギア RS-F ドライバー", ["プロギア|prgr", "rsf"], []),
    DriverModel("dr_prgr_rs", "プロギア", "RS", "—",
                "プロギア RS ドライバー", ["プロギア|prgr", "=rs"], ["rs5", "rsf", "rsjust", "rsduo"]),
    DriverModel("dr_tsuruya_axel", "つるや", "AXEL GF", "—",
                "つるや アクセル GF ドライバー", ["つるや|tsuruya", "アクセル|axel"], []),
    DriverModel("dr_cw_roguestar", "キャロウェイ", "ROGUE STAR", "2018",
                "キャロウェイ ROGUE STAR ドライバー", ["roguestar"], []),
    DriverModel("dr_tm_mgloire", "テーラーメイド", "M グローレ", "2018",
                "テーラーメイド Mグローレ ドライバー", ["mグローレ|mgloire"], []),
    DriverModel("dr_tm_gloire", "テーラーメイド", "グローレ", "—",
                "テーラーメイド グローレ ドライバー", ["グローレ|gloire"],
                ["mグローレ|mgloire", "ステルスグローレ|stealthgloire"]),
    DriverModel("dr_tm_stealthgloire", "テーラーメイド", "ステルスグローレ+", "2022",
                "テーラーメイド ステルスグローレ ドライバー", ["ステルスグローレ|stealthgloire"], []),
    DriverModel("dr_hm_tw747", "本間", "TW747", "2019",
                "本間 TW747 ドライバー", ["tw747"], []),
    DriverModel("dr_mz_promodel_e", "ミズノ", "プロモデル E", "—",
                "ミズノ プロモデル E ドライバー", ["ミズノ|mizuno", "プロモデルe"], []),
    DriverModel("dr_mz_promodel_s", "ミズノ", "プロモデル S", "—",
                "ミズノ プロモデル S ドライバー", ["ミズノ|mizuno", "プロモデルs"], []),
    DriverModel("dr_pxg_0811", "PXG", "0811", "—",
                "PXG 0811 ドライバー", ["pxg", "0811"], []),
    DriverModel("dr_tm_r11s", "テーラーメイド", "R11S", "2012",
                "テーラーメイド R11S ドライバー", ["r11s"], []),
    DriverModel("dr_cw_gbbepic", "キャロウェイ", "GBB EPIC", "2017",
                "キャロウェイ GBB EPIC ドライバー", ["gbbepic|epicforged"], []),
    DriverModel("dr_ti_909", "タイトリスト", "909", "—",
                "タイトリスト 909 ドライバー", ["タイトリスト|titleist", "909"], []),
    DriverModel("dr_ping_g10", "ピン", "G10", "—",
                "ピン G10 ドライバー", ["ピン|ping", "=g10"], []),
    DriverModel("dr_14_ct112", "フォーティーン", "CT112", "—",
                "フォーティーン CT112 ドライバー", ["ct112"], []),
    DriverModel("dr_tm_r1", "テーラーメイド", "R1", "2013",
                "テーラーメイド R1 ドライバー", ["テーラーメイド|taylormade", "=r1"], []),
    DriverModel("dr_tm_qi35", "テーラーメイド", "Qi35", "2025",
                "テーラーメイド Qi35 ドライバー", ["qi35"], []),
    DriverModel("dr_mazel_mini", "MAZEL", "SPEED ミニドライバー", "—",
                "MAZEL ミニ ドライバー", ["mazel|マゼル"], []),
    DriverModel("dr_tm_brnrmini", "テーラーメイド", "BRNR Mini", "2023",
                "テーラーメイド BRNR ミニ ドライバー", ["brnr"], []),
    # --- フェアウェイウッド ---
    DriverModel("fw_tm_rbz", "テーラーメイド", "RBZ（ロケットボールズ）", "—",
                "テーラーメイド RBZ ロケットボールズ フェアウェイウッド",
                ["rbz|ロケットボールズ|rocketballz"], [], category="fw"),
    DriverModel("fw_tm_m2", "テーラーメイド", "M2 FW", "2017",
                "テーラーメイド M2 フェアウェイウッド", ["テーラーメイド|taylormade", "=m2"], [], category="fw"),
    # --- ユーティリティ ---
    DriverModel("ut_adams_idea", "アダムス", "IDEA", "—",
                "アダムス イデア ユーティリティ", ["アダムス|adams", "イデア|idea"], [], category="ut"),
    DriverModel("ut_magicmulligan", "マジックマリガン", "ユーティリティ", "—",
                "マジックマリガン ユーティリティ", ["マジックマリガン|magicmulligan"], [], category="ut"),
    # --- アイアン ---
    DriverModel("ir_ping_i540", "ピン", "i540", "2024",
                "ピン i540 アイアン", ["i540"], [], category="iron"),
    DriverModel("ir_ping_i240", "ピン", "i240", "2023",
                "ピン i240 アイアン", ["i240"], [], category="iron"),
    DriverModel("ir_ping_i530", "ピン", "i530", "2024",
                "ピン i530 アイアン", ["i530"], [], category="iron"),
    DriverModel("ir_pxg_0311", "PXG", "0311 アイアン", "—",
                "PXG 0311 アイアン", ["pxg", "0311"], [], category="iron"),
    DriverModel("ir_lynx_master", "リンクス", "マスターモデル", "—",
                "リンクス マスターモデル アイアン", ["リンクス|lynx", "マスター|master"], [], category="iron"),
    DriverModel("ir_prgr_zoom", "プロギア", "ZOOM i202", "—",
                "プロギア ZOOM アイアン", ["プロギア|prgr", "zoom"], [], category="iron"),
    DriverModel("ir_ping_g25", "ピン", "G25 アイアン", "—",
                "ピン G25 アイアン", ["ピン|ping", "=g25"], [], category="iron"),

    # ==================== チッパー ====================
    DriverModel("ch_ping_chipr", "ピン", "CHIPR", "2022",
                "ピン CHIPR チッパー", ["chipr"], [], category="chipper"),
    DriverModel("ch_cleveland_smartsole", "クリーブランド", "Smart Sole", "—",
                "クリーブランド スマートソール チッパー",
                ["smartsole|スマートソール"], [], category="chipper"),
    DriverModel("ch_kasco_dolphin", "キャスコ", "ドルフィン チッパー", "—",
                "キャスコ ドルフィン チッパー", ["ドルフィン|dolphin"], [], category="chipper"),
    DriverModel("ch_odyssey_xact", "オデッセイ", "X-ACT チッパー", "—",
                "オデッセイ X-ACT チッパー", ["xact|エグザクト"], [], category="chipper"),
    DriverModel("ch_wilson_harmonized", "ウィルソン", "Harmonized チッパー", "—",
                "ウィルソン ハーモナイズド チッパー",
                ["ウィルソン|wilson|harmonized|ハーモナイズド"], [], category="chipper"),
    DriverModel("ch_lynx", "リンクス", "リンクス チッパー", "—",
                "リンクス チッパー", ["リンクス|lynx"], [], category="chipper"),
    DriverModel("ch_fourteen", "フォーティーン", "フォーティーン チッパー", "—",
                "フォーティーン チッパー", ["フォーティーン|fourteen"], [], category="chipper"),
]

CATALOG_BY_KEY = {m.key: m for m in CATALOG}
